name: super_repository
description: A new Flutter project.
publish_to: abdullahAlwajih
version: 0.1.116
homepage: https://github.com/abdullahAlwajih/Super-Repository

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # remote
  dio: ^4.0.6
  connectivity_plus: ^3.0.2

  # local
  get_storage: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1